///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace phar
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the LoginRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    [RepositoryFolder("53bb0259-6ab2-4744-8bc9-29505775dd9e")]
    public partial class LoginRepository : RepoGenBaseFolder
    {
        static LoginRepository instance = new LoginRepository();
        LoginRepositoryFolders.POSAppUWPAppFolder _posappuwp;

        /// <summary>
        /// Gets the singleton class instance representing the LoginRepository element repository.
        /// </summary>
        [RepositoryFolder("53bb0259-6ab2-4744-8bc9-29505775dd9e")]
        public static LoginRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public LoginRepository() 
            : base("LoginRepository", "/", null, 0, false, "53bb0259-6ab2-4744-8bc9-29505775dd9e", ".\\RepositoryImages\\LoginRepository53bb0259.rximgres")
        {
            _posappuwp = new LoginRepositoryFolders.POSAppUWPAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("53bb0259-6ab2-4744-8bc9-29505775dd9e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The POSAppUWP folder.
        /// </summary>
        [RepositoryFolder("89e50b1d-a76e-4863-8a3b-3b143069a236")]
        public virtual LoginRepositoryFolders.POSAppUWPAppFolder POSAppUWP
        {
            get { return _posappuwp; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    public partial class LoginRepositoryFolders
    {
        /// <summary>
        /// The POSAppUWPAppFolder folder.
        /// </summary>
        [RepositoryFolder("89e50b1d-a76e-4863-8a3b-3b143069a236")]
        public partial class POSAppUWPAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _farmaciaInfo;
            RepoItemInfo _textblockInfo;
            RepoItemInfo _aseguratedeescribirlasucursalcorrecInfo;
            RepoItemInfo _sucursalInfo;
            RepoItemInfo _contentelementInfo;
            RepoItemInfo _sucursal1Info;
            RepoItemInfo _formatovalidoparaadministradorInfo;
            RepoItemInfo _textusuarioInfo;
            RepoItemInfo _contentelement1Info;
            RepoItemInfo _textusuario1Info;
            RepoItemInfo _contrasenaInfo;
            RepoItemInfo _contentelement2Info;
            RepoItemInfo _contrasena1Info;
            RepoItemInfo _iniciarInfo;
            RepoItemInfo _iniciar1Info;
            RepoItemInfo _textblock1Info;
            RepoItemInfo _textblock2Info;
            RepoItemInfo _progressbarInfo;
            RepoItemInfo _pospharmacyv12520desarrolladopoInfo;
            RepoItemInfo _imageInfo;

            /// <summary>
            /// Creates a new POSAppUWP  folder.
            /// </summary>
            public POSAppUWPAppFolder(RepoGenBaseFolder parentFolder) :
                    base("POSAppUWP", "/winapp[@packagename='9a5b5a8e-47e0-45c9-bc2e-6af104a34ddb']", parentFolder, 30000, null, true, "89e50b1d-a76e-4863-8a3b-3b143069a236", "")
            {
                _farmaciaInfo = new RepoItemInfo(this, "Farmacia", "text[@name='Farmacia']", 30000, null, "a927ce49-a2f2-4f95-af38-fbec4f050ff9");
                _textblockInfo = new RepoItemInfo(this, "TextBlock", "text[2]", 30000, null, "59114c2d-8612-4c42-a3dc-50442a6e87d8");
                _aseguratedeescribirlasucursalcorrecInfo = new RepoItemInfo(this, "AsegurateDeEscribirLaSucursalCorrec", "text[@name~'^Asegurate\\ de\\ escribir\\ la\\ ']", 30000, null, "0b425cfd-5bd6-477a-aef0-06bd10d24399");
                _sucursalInfo = new RepoItemInfo(this, "Sucursal", "?/?/text[@name='Sucursal']", 30000, null, "30b6595a-4207-4062-9d5b-0851fcb75695");
                _contentelementInfo = new RepoItemInfo(this, "ContentElement", "?/?/container[@automationid='ContentElement']", 30000, null, "98adb5dc-e61a-434a-b93e-ba72a3025582");
                _sucursal1Info = new RepoItemInfo(this, "Sucursal1", "text[@name='Sucursal']", 30000, null, "c4b6cb62-cf41-4b43-a8f7-43342e50808e");
                _formatovalidoparaadministradorInfo = new RepoItemInfo(this, "FormatoValidoParaAdministrador", "text[@name~'^Formato\\ válido\\ para\\ Admin']", 30000, null, "7e1e78dd-5d11-49e4-9653-eb0b1bed4f84");
                _textusuarioInfo = new RepoItemInfo(this, "TextUsuario", "?/?/text[@name='  Usuario']", 30000, null, "9844e31c-be78-4eca-bbd0-a09a9ac5fb5f");
                _contentelement1Info = new RepoItemInfo(this, "ContentElement1", "text[@name='  Usuario']/container[@automationid='ContentElement']", 30000, null, "84a693ca-0a2c-4772-8e1e-ab2a77e7bf17");
                _textusuario1Info = new RepoItemInfo(this, "TextUsuario1", "text[@name='  Usuario']", 30000, null, "2ef4b1d7-e8e8-46cf-8614-da9eac5649af");
                _contrasenaInfo = new RepoItemInfo(this, "Contrasena", "?/?/text[@name='Contraseña']", 30000, null, "11f060b7-df43-4d30-9cd0-afdb73c3c8d3");
                _contentelement2Info = new RepoItemInfo(this, "ContentElement2", "text[@name='Contraseña']/container[@automationid='ContentElement']", 30000, null, "735a15bf-472d-4967-a479-09c90bfbc12e");
                _contrasena1Info = new RepoItemInfo(this, "Contrasena1", "text[@name='Contraseña']", 30000, null, "a2d4fab7-7775-43b2-b399-82c3899b4e91");
                _iniciarInfo = new RepoItemInfo(this, "Iniciar", "?/?/text[@name='Iniciar']", 30000, null, "3ad11787-38a5-492b-88d0-0a850d09322c");
                _iniciar1Info = new RepoItemInfo(this, "Iniciar1", "button[@name='Iniciar']", 30000, null, "b24acee5-3af9-48e4-af19-ea3ac737cfd7");
                _textblock1Info = new RepoItemInfo(this, "TextBlock1", "text[8]", 30000, null, "04bc1203-55e6-4956-b342-99a52609332a");
                _textblock2Info = new RepoItemInfo(this, "TextBlock2", "text[9]", 30000, null, "cbfe8a25-c3da-4899-9553-8835e4532fbb");
                _progressbarInfo = new RepoItemInfo(this, "ProgressBar", "progressbar[@classname='ProgressBar']", 30000, null, "55619476-9a7b-4fff-8819-88964f33bfba");
                _pospharmacyv12520desarrolladopoInfo = new RepoItemInfo(this, "POSPharmacyV12520DesarrolladoPo", "text[@name~'^POS\\ Pharmacy\\ v\\.\\ 1\\.25\\.2\\.0\\ ']", 30000, null, "4dedbcd0-d040-4c88-afe4-77eae5b013a0");
                _imageInfo = new RepoItemInfo(this, "Image", "picture[@classname='Image']", 30000, null, "45d04abe-dbed-4e1e-8167-2561570249b2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("89e50b1d-a76e-4863-8a3b-3b143069a236")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("89e50b1d-a76e-4863-8a3b-3b143069a236")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Farmacia item.
            /// </summary>
            [RepositoryItem("a927ce49-a2f2-4f95-af38-fbec4f050ff9")]
            public virtual Ranorex.Text Farmacia
            {
                get
                {
                    return _farmaciaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Farmacia item info.
            /// </summary>
            [RepositoryItemInfo("a927ce49-a2f2-4f95-af38-fbec4f050ff9")]
            public virtual RepoItemInfo FarmaciaInfo
            {
                get
                {
                    return _farmaciaInfo;
                }
            }

            /// <summary>
            /// The TextBlock item.
            /// </summary>
            [RepositoryItem("59114c2d-8612-4c42-a3dc-50442a6e87d8")]
            public virtual Ranorex.Text TextBlock
            {
                get
                {
                    return _textblockInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextBlock item info.
            /// </summary>
            [RepositoryItemInfo("59114c2d-8612-4c42-a3dc-50442a6e87d8")]
            public virtual RepoItemInfo TextBlockInfo
            {
                get
                {
                    return _textblockInfo;
                }
            }

            /// <summary>
            /// The AsegurateDeEscribirLaSucursalCorrec item.
            /// </summary>
            [RepositoryItem("0b425cfd-5bd6-477a-aef0-06bd10d24399")]
            public virtual Ranorex.Text AsegurateDeEscribirLaSucursalCorrec
            {
                get
                {
                    return _aseguratedeescribirlasucursalcorrecInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AsegurateDeEscribirLaSucursalCorrec item info.
            /// </summary>
            [RepositoryItemInfo("0b425cfd-5bd6-477a-aef0-06bd10d24399")]
            public virtual RepoItemInfo AsegurateDeEscribirLaSucursalCorrecInfo
            {
                get
                {
                    return _aseguratedeescribirlasucursalcorrecInfo;
                }
            }

            /// <summary>
            /// The Sucursal item.
            /// </summary>
            [RepositoryItem("30b6595a-4207-4062-9d5b-0851fcb75695")]
            public virtual Ranorex.Text Sucursal
            {
                get
                {
                    return _sucursalInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Sucursal item info.
            /// </summary>
            [RepositoryItemInfo("30b6595a-4207-4062-9d5b-0851fcb75695")]
            public virtual RepoItemInfo SucursalInfo
            {
                get
                {
                    return _sucursalInfo;
                }
            }

            /// <summary>
            /// The ContentElement item.
            /// </summary>
            [RepositoryItem("98adb5dc-e61a-434a-b93e-ba72a3025582")]
            public virtual Ranorex.Container ContentElement
            {
                get
                {
                    return _contentelementInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContentElement item info.
            /// </summary>
            [RepositoryItemInfo("98adb5dc-e61a-434a-b93e-ba72a3025582")]
            public virtual RepoItemInfo ContentElementInfo
            {
                get
                {
                    return _contentelementInfo;
                }
            }

            /// <summary>
            /// The Sucursal1 item.
            /// </summary>
            [RepositoryItem("c4b6cb62-cf41-4b43-a8f7-43342e50808e")]
            public virtual Ranorex.Text Sucursal1
            {
                get
                {
                    return _sucursal1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Sucursal1 item info.
            /// </summary>
            [RepositoryItemInfo("c4b6cb62-cf41-4b43-a8f7-43342e50808e")]
            public virtual RepoItemInfo Sucursal1Info
            {
                get
                {
                    return _sucursal1Info;
                }
            }

            /// <summary>
            /// The FormatoValidoParaAdministrador item.
            /// </summary>
            [RepositoryItem("7e1e78dd-5d11-49e4-9653-eb0b1bed4f84")]
            public virtual Ranorex.Text FormatoValidoParaAdministrador
            {
                get
                {
                    return _formatovalidoparaadministradorInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FormatoValidoParaAdministrador item info.
            /// </summary>
            [RepositoryItemInfo("7e1e78dd-5d11-49e4-9653-eb0b1bed4f84")]
            public virtual RepoItemInfo FormatoValidoParaAdministradorInfo
            {
                get
                {
                    return _formatovalidoparaadministradorInfo;
                }
            }

            /// <summary>
            /// The TextUsuario item.
            /// </summary>
            [RepositoryItem("9844e31c-be78-4eca-bbd0-a09a9ac5fb5f")]
            public virtual Ranorex.Text TextUsuario
            {
                get
                {
                    return _textusuarioInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextUsuario item info.
            /// </summary>
            [RepositoryItemInfo("9844e31c-be78-4eca-bbd0-a09a9ac5fb5f")]
            public virtual RepoItemInfo TextUsuarioInfo
            {
                get
                {
                    return _textusuarioInfo;
                }
            }

            /// <summary>
            /// The ContentElement1 item.
            /// </summary>
            [RepositoryItem("84a693ca-0a2c-4772-8e1e-ab2a77e7bf17")]
            public virtual Ranorex.Container ContentElement1
            {
                get
                {
                    return _contentelement1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContentElement1 item info.
            /// </summary>
            [RepositoryItemInfo("84a693ca-0a2c-4772-8e1e-ab2a77e7bf17")]
            public virtual RepoItemInfo ContentElement1Info
            {
                get
                {
                    return _contentelement1Info;
                }
            }

            /// <summary>
            /// The TextUsuario1 item.
            /// </summary>
            [RepositoryItem("2ef4b1d7-e8e8-46cf-8614-da9eac5649af")]
            public virtual Ranorex.Text TextUsuario1
            {
                get
                {
                    return _textusuario1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextUsuario1 item info.
            /// </summary>
            [RepositoryItemInfo("2ef4b1d7-e8e8-46cf-8614-da9eac5649af")]
            public virtual RepoItemInfo TextUsuario1Info
            {
                get
                {
                    return _textusuario1Info;
                }
            }

            /// <summary>
            /// The Contrasena item.
            /// </summary>
            [RepositoryItem("11f060b7-df43-4d30-9cd0-afdb73c3c8d3")]
            public virtual Ranorex.Text Contrasena
            {
                get
                {
                    return _contrasenaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Contrasena item info.
            /// </summary>
            [RepositoryItemInfo("11f060b7-df43-4d30-9cd0-afdb73c3c8d3")]
            public virtual RepoItemInfo ContrasenaInfo
            {
                get
                {
                    return _contrasenaInfo;
                }
            }

            /// <summary>
            /// The ContentElement2 item.
            /// </summary>
            [RepositoryItem("735a15bf-472d-4967-a479-09c90bfbc12e")]
            public virtual Ranorex.Container ContentElement2
            {
                get
                {
                    return _contentelement2Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContentElement2 item info.
            /// </summary>
            [RepositoryItemInfo("735a15bf-472d-4967-a479-09c90bfbc12e")]
            public virtual RepoItemInfo ContentElement2Info
            {
                get
                {
                    return _contentelement2Info;
                }
            }

            /// <summary>
            /// The Contrasena1 item.
            /// </summary>
            [RepositoryItem("a2d4fab7-7775-43b2-b399-82c3899b4e91")]
            public virtual Ranorex.Text Contrasena1
            {
                get
                {
                    return _contrasena1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Contrasena1 item info.
            /// </summary>
            [RepositoryItemInfo("a2d4fab7-7775-43b2-b399-82c3899b4e91")]
            public virtual RepoItemInfo Contrasena1Info
            {
                get
                {
                    return _contrasena1Info;
                }
            }

            /// <summary>
            /// The Iniciar item.
            /// </summary>
            [RepositoryItem("3ad11787-38a5-492b-88d0-0a850d09322c")]
            public virtual Ranorex.Text Iniciar
            {
                get
                {
                    return _iniciarInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Iniciar item info.
            /// </summary>
            [RepositoryItemInfo("3ad11787-38a5-492b-88d0-0a850d09322c")]
            public virtual RepoItemInfo IniciarInfo
            {
                get
                {
                    return _iniciarInfo;
                }
            }

            /// <summary>
            /// The Iniciar1 item.
            /// </summary>
            [RepositoryItem("b24acee5-3af9-48e4-af19-ea3ac737cfd7")]
            public virtual Ranorex.Button Iniciar1
            {
                get
                {
                    return _iniciar1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Iniciar1 item info.
            /// </summary>
            [RepositoryItemInfo("b24acee5-3af9-48e4-af19-ea3ac737cfd7")]
            public virtual RepoItemInfo Iniciar1Info
            {
                get
                {
                    return _iniciar1Info;
                }
            }

            /// <summary>
            /// The TextBlock1 item.
            /// </summary>
            [RepositoryItem("04bc1203-55e6-4956-b342-99a52609332a")]
            public virtual Ranorex.Text TextBlock1
            {
                get
                {
                    return _textblock1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextBlock1 item info.
            /// </summary>
            [RepositoryItemInfo("04bc1203-55e6-4956-b342-99a52609332a")]
            public virtual RepoItemInfo TextBlock1Info
            {
                get
                {
                    return _textblock1Info;
                }
            }

            /// <summary>
            /// The TextBlock2 item.
            /// </summary>
            [RepositoryItem("cbfe8a25-c3da-4899-9553-8835e4532fbb")]
            public virtual Ranorex.Text TextBlock2
            {
                get
                {
                    return _textblock2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextBlock2 item info.
            /// </summary>
            [RepositoryItemInfo("cbfe8a25-c3da-4899-9553-8835e4532fbb")]
            public virtual RepoItemInfo TextBlock2Info
            {
                get
                {
                    return _textblock2Info;
                }
            }

            /// <summary>
            /// The ProgressBar item.
            /// </summary>
            [RepositoryItem("55619476-9a7b-4fff-8819-88964f33bfba")]
            public virtual Ranorex.ProgressBar ProgressBar
            {
                get
                {
                    return _progressbarInfo.CreateAdapter<Ranorex.ProgressBar>(true);
                }
            }

            /// <summary>
            /// The ProgressBar item info.
            /// </summary>
            [RepositoryItemInfo("55619476-9a7b-4fff-8819-88964f33bfba")]
            public virtual RepoItemInfo ProgressBarInfo
            {
                get
                {
                    return _progressbarInfo;
                }
            }

            /// <summary>
            /// The POSPharmacyV12520DesarrolladoPo item.
            /// </summary>
            [RepositoryItem("4dedbcd0-d040-4c88-afe4-77eae5b013a0")]
            public virtual Ranorex.Text POSPharmacyV12520DesarrolladoPo
            {
                get
                {
                    return _pospharmacyv12520desarrolladopoInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The POSPharmacyV12520DesarrolladoPo item info.
            /// </summary>
            [RepositoryItemInfo("4dedbcd0-d040-4c88-afe4-77eae5b013a0")]
            public virtual RepoItemInfo POSPharmacyV12520DesarrolladoPoInfo
            {
                get
                {
                    return _pospharmacyv12520desarrolladopoInfo;
                }
            }

            /// <summary>
            /// The Image item.
            /// </summary>
            [RepositoryItem("45d04abe-dbed-4e1e-8167-2561570249b2")]
            public virtual Ranorex.Picture Image
            {
                get
                {
                    return _imageInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The Image item info.
            /// </summary>
            [RepositoryItemInfo("45d04abe-dbed-4e1e-8167-2561570249b2")]
            public virtual RepoItemInfo ImageInfo
            {
                get
                {
                    return _imageInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}